spring.application.name=jpa

spring.datasource.url=jdbc:log4jdbc:postgresql://192.168.199.11:5432/crmdb
spring.datasource.username=appcrm
spring.datasource.password=appcrm2302!
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true